import type { Metadata } from "next";
import "./globals.css";
import { Root } from '@/components/layouts/root';
import { LayoutAppSchemaProps } from '@/types/root';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: LayoutAppSchemaProps) {
  return (
    <Root>
      {children}
    </Root>
  );
}
